### PR TITLE
fixed cmake files for win32

### PR DESCRIPTION
**Pull request by TheElementalOfCreation**
fixed error about not finding exe target (cause it is never actually specified in the first place)

### CODE REVIEW

**Comment by TheElementalOfCreation** [comment]
wait, I messed up give me a sec to fix it.

**Comment by TheElementalOfCreation** [comment]
Okay, NOW it is fixed.

**Comment by pixelherodev** [comment]
I'm going to test this soon

**Comment by pixelherodev** [comment]
Examining the files, this looks good, but I'm going to make sure to test it before merging

**Comment by pixelherodev** [comment]
Hold on - is this for Cygwin? What environment did you use to build this? From the Win32, I'd assume VS?

**Comment by TheElementalOfCreation** [comment]
Vs. Mind you, its going to be a LONG time before all of this actually can build in vs because it depends on so many linux/cygwin dependent things. I managed to get bits and pieces compuled with these changes though.

**Comment by pixelherodev** [comment]
Yeah, I'm working on getting scas working in VS now, which is a needed first step

**Comment by pixelherodev** [comment]
99% sure I fixed this with a recent cleanup commit.

**Pull request closed without merging**
